import type { FontPair } from "./types";

export const FONT_PAIRS: FontPair[] = [
  {
    heading: "Inter",
    body: "Inter",
    vibes: ["modern-saas", "minimal", "dark-tech"],
    source: "google",
  },
  {
    heading: "Space Grotesk",
    body: "Inter",
    vibes: ["modern-saas", "dark-tech", "soft-neo-tech"],
    source: "google",
  },
  {
    heading: "DM Sans",
    body: "DM Sans",
    vibes: ["minimal", "modern-saas", "gradient-bloom"],
    source: "google",
  },
  {
    heading: "Poppins",
    body: "Nunito",
    vibes: ["pastel", "modern-saas", "gradient-bloom"],
    source: "google",
  },
  {
    heading: "Manrope",
    body: "Inter",
    vibes: ["modern-saas", "minimal", "soft-neo-tech"],
    source: "google",
  },
  {
    heading: "Montserrat",
    body: "Lato",
    vibes: ["modern-saas", "pastel"],
    source: "google",
  },
  {
    heading: "Rubik",
    body: "Inter",
    vibes: ["modern-saas", "pastel", "retro-pixel"],
    source: "google",
  },
  {
    heading: "Figtree",
    body: "Figtree",
    vibes: ["minimal", "pastel"],
    source: "google",
  },
  {
    heading: "Work Sans",
    body: "Source Sans Pro",
    vibes: ["modern-saas", "dark-tech", "cyber-mint"],
    source: "google",
  },
  {
    heading: "IBM Plex Sans",
    body: "IBM Plex Serif",
    vibes: ["minimal", "luxury", "warm-editorial"],
    source: "google",
  },
  {
    heading: "Playfair Display",
    body: "Lora",
    vibes: ["luxury", "warm-editorial", "magazine-brutalism"],
    source: "google",
  },
  {
    heading: "Cormorant Garamond",
    body: "Inter",
    vibes: ["luxury", "warm-editorial"],
    source: "google",
  },
  {
    heading: "Libre Baskerville",
    body: "Nunito",
    vibes: ["warm-editorial", "magazine-brutalism"],
    source: "google",
  },
  {
    heading: "Source Code Pro",
    body: "Inter",
    vibes: ["dark-tech", "minimal", "retro-pixel"],
    source: "google",
  },
  {
    heading: "SF Pro Display",
    body: "SF Pro Text",
    vibes: ["modern-saas", "minimal"],
    source: "system",
    notes: "Apple system font family (San Francisco).",
  },
  {
    heading: "Segoe UI",
    body: "Segoe UI",
    vibes: ["modern-saas", "magazine-brutalism"],
    source: "system",
    notes: "Windows system UI font.",
  },
  {
    heading: "Neue Haas Grotesk",
    body: "Neue Haas Grotesk",
    vibes: ["luxury", "modern-saas"],
    source: "premium",
    notes: "Premium grotesque, requires commercial license.",
  },
  {
    heading: "GT Walsheim",
    body: "GT Walsheim",
    vibes: ["pastel", "gradient-bloom", "retro-pixel"],
    source: "premium",
    notes: "Rounded geometric sans, requires commercial license.",
  },
  {
    heading: "Circular",
    body: "Circular",
    vibes: ["modern-saas", "luxury"],
    source: "premium",
    notes: "Modern geometric sans, requires commercial license.",
  },
  {
    heading: "Söhne",
    body: "Söhne",
    vibes: ["dark-tech", "magazine-brutalism"],
    source: "premium",
    notes: "Grotesk by Klim Type Foundry, requires license.",
  },
  {
    heading: "Maison Neue",
    body: "Maison Neue",
    vibes: ["minimal", "luxury"],
    source: "premium",
    notes: "Neo-grotesk, requires license.",
  },
];
