import type { VibePreset, VibeId } from "./types";

export const VIBE_PRESETS: Record<VibeId, VibePreset> = {
  minimal: {
    id: "minimal",
    label: "Minimal",
    description: "Soft neutrals, subtle borders and calm UI surfaces.",
    isDarkUi: false,
    palette: {
      primary: "#0F766E",
      secondary: "#475569",
      accent: "#F97316",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#E5E7EB",
      text: "#020617",
      textMuted: "#64748B",
      borderSubtle: "#E5E7EB",
      borderStrong: "#CBD5F5",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "xl", weight: 600, style: "normal" },
      body: { size: "sm", weight: 400, style: "normal" },
      accent: { size: "xs", weight: 500, style: "italic" },
    },
    colorVariations: [
      { primary: "#0F766E", secondary: "#475569", accent: "#F97316" },
      { primary: "#0D9488", secondary: "#64748B", accent: "#FB923C" },
      { primary: "#14B8A6", secondary: "#78716C", accent: "#FDBA74" },
      { primary: "#2DD4BF", secondary: "#9CA3AF", accent: "#FCD34D" },
      { primary: "#06B6D4", secondary: "#6B7280", accent: "#FBBF24" },
    ],
  },

  "modern-saas": {
    id: "modern-saas",
    label: "Modern SaaS",
    description:
      "Bright primary, layered cards and rounded buttons for product UIs.",
    isDarkUi: false,
    palette: {
      primary: "#2563EB",
      secondary: "#4F46E5",
      accent: "#F97316",
      background: "#F3F4F6",
      surface: "#FFFFFF",
      surfaceAlt: "#E5E7EB",
      text: "#020617",
      textMuted: "#6B7280",
      borderSubtle: "#E5E7EB",
      borderStrong: "#CBD5F5",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 700, style: "normal" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 600, style: "normal" },
    },
    colorVariations: [
      { primary: "#2563EB", secondary: "#4F46E5", accent: "#F97316" },
      { primary: "#1D4ED8", secondary: "#6366F1", accent: "#FB923C" },
      { primary: "#1E40AF", secondary: "#818CF8", accent: "#FDBA74" },
      { primary: "#3B82F6", secondary: "#A5B4FC", accent: "#FCD34D" },
      { primary: "#60A5FA", secondary: "#C4B5FD", accent: "#FBBF24" },
    ],
  },

  brutalist: {
    id: "brutalist",
    label: "Brutalist",
    description: "Sharp corners, strong borders and unapologetic colors.",
    isDarkUi: false,
    palette: {
      primary: "#111827",
      secondary: "#F97316",
      accent: "#EC4899",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#F3F4F6",
      text: "#020617",
      textMuted: "#4B5563",
      borderSubtle: "#E5E7EB",
      borderStrong: "#111827",
    },
    ui: {
      buttonPrimary: { radius: "none", shadow: "none", border: "strong" },
      buttonSecondary: { radius: "none", shadow: "none", border: "strong" },
      card: { radius: "sm", shadow: "none", border: "strong" },
    },
    typography: {
      heading: { size: "2xl", weight: 800, style: "normal" },
      body: { size: "sm", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 700, style: "normal" },
    },
    colorVariations: [
      { primary: "#111827", secondary: "#F97316", accent: "#EC4899" },
      { primary: "#1F2937", secondary: "#FB923C", accent: "#F472B6" },
      { primary: "#374151", secondary: "#FDBA74", accent: "#F9A8D4" },
      { primary: "#0F172A", secondary: "#FCD34D", accent: "#BE123C" },
      { primary: "#18181B", secondary: "#EF4444", accent: "#7C2D12" },
    ],
  },

  pastel: {
    id: "pastel",
    label: "Pastel / Friendly",
    description: "Soft backgrounds, candy accents and rounded pill buttons.",
    isDarkUi: false,
    palette: {
      primary: "#FB7185",
      secondary: "#38BDF8",
      accent: "#A78BFA",
      background: "#FEFCE8",
      surface: "#FFFBEB",
      surfaceAlt: "#F9FAFB",
      text: "#1F2933",
      textMuted: "#6B7280",
      borderSubtle: "#FDE68A",
      borderStrong: "#F97373",
    },
    ui: {
      buttonPrimary: { radius: "full", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "full", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "xl", weight: 700, style: "italic" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 500, style: "italic" },
    },
    colorVariations: [
      { primary: "#FB7185", secondary: "#38BDF8", accent: "#A78BFA" },
      { primary: "#F472B6", secondary: "#7DD3FC", accent: "#C4B5FD" },
      { primary: "#F9A8D4", secondary: "#BAE6FD", accent: "#DDD6FE" },
      { primary: "#F87171", secondary: "#0EA5E9", accent: "#E9D5FF" },
      { primary: "#FCA5A5", secondary: "#06B6D4", accent: "#F3E8FF" },
    ],
  },

  "dark-tech": {
    id: "dark-tech",
    label: "Dark Tech",
    description: "Deep dark surfaces with neon-like accents.",
    isDarkUi: true,
    palette: {
      primary: "#38BDF8",
      secondary: "#6366F1",
      accent: "#22C55E",
      background: "#020617",
      surface: "#0F172A",
      surfaceAlt: "#1E293B",
      text: "#F1F5F9",
      textMuted: "#94A3B8",
      borderSubtle: "#1E293B",
      borderStrong: "#38BDF8",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "strong", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 700, style: "normal" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 600, style: "normal" },
    },
    colorVariations: [
      { primary: "#38BDF8", secondary: "#6366F1", accent: "#22C55E" },
      { primary: "#7DD3FC", secondary: "#818CF8", accent: "#4ADE80" },
      { primary: "#0EA5E9", secondary: "#A5B4FC", accent: "#86EFAC" },
      { primary: "#06B6D4", secondary: "#C4B5FD", accent: "#DCFCE7" },
      { primary: "#67E8F9", secondary: "#E9D5FF", accent: "#BBFF00" },
    ],
  },

  luxury: {
    id: "luxury",
    label: "Luxury",
    description: "Deep backgrounds, gold accents and high-contrast serif.",
    isDarkUi: true,
    palette: {
      primary: "#1F2937",
      secondary: "#D97706",
      accent: "#FBBF24",
      background: "#0F172A",
      surface: "#1E293B",
      surfaceAlt: "#334155",
      text: "#F8FAFC",
      textMuted: "#CBD5E1",
      borderSubtle: "#475569",
      borderStrong: "#D97706",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "strong", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 600, style: "italic" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 700, style: "normal" },
    },
    colorVariations: [
      { primary: "#1F2937", secondary: "#D97706", accent: "#FBBF24" },
      { primary: "#2D3748", secondary: "#F59E0B", accent: "#FCD34D" },
      { primary: "#374151", secondary: "#F97316", accent: "#FCA5A5" },
      { primary: "#1A202C", secondary: "#B45309", accent: "#FBBF24" },
      { primary: "#2D3748", secondary: "#92400E", accent: "#FEF08A" },
    ],
  },

  "soft-neo-tech": {
    id: "soft-neo-tech",
    label: "Soft Neo-Tech",
    description: "Soft dark UI with muted neon and rounded surfaces.",
    isDarkUi: true,
    palette: {
      primary: "#8B5CF6",
      secondary: "#EC4899",
      accent: "#06B6D4",
      background: "#1F1F2E",
      surface: "#2D2D44",
      surfaceAlt: "#3D3D55",
      text: "#E8E8F0",
      textMuted: "#A8A8C0",
      borderSubtle: "#3D3D55",
      borderStrong: "#8B5CF6",
    },
    ui: {
      buttonPrimary: { radius: "full", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "full", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "xl", weight: 600, style: "normal" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 500, style: "italic" },
    },
    colorVariations: [
      { primary: "#8B5CF6", secondary: "#EC4899", accent: "#06B6D4" },
      { primary: "#A78BFA", secondary: "#F472B6", accent: "#22D3EE" },
      { primary: "#C4B5FD", secondary: "#F9A8D4", accent: "#67E8F9" },
      { primary: "#DDD6FE", secondary: "#FBCFE8", accent: "#A5F3FC" },
      { primary: "#F3E8FF", secondary: "#FEE2E8", accent: "#CFFAFE" },
    ],
  },

  "gradient-bloom": {
    id: "gradient-bloom",
    label: "Gradient Bloom",
    description: "Bright gradients and playful landing-page energy.",
    isDarkUi: false,
    palette: {
      primary: "#EC4899",
      secondary: "#F97316",
      accent: "#FBBF24",
      background: "#FFFBEB",
      surface: "#FFFFFF",
      surfaceAlt: "#FEF3C7",
      text: "#1F2937",
      textMuted: "#6B7280",
      borderSubtle: "#FDE68A",
      borderStrong: "#FBBF24",
    },
    ui: {
      buttonPrimary: { radius: "full", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "full", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 700, style: "italic" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 600, style: "normal" },
    },
    colorVariations: [
      { primary: "#EC4899", secondary: "#F97316", accent: "#FBBF24" },
      { primary: "#F472B6", secondary: "#FB923C", accent: "#FCD34D" },
      { primary: "#F9A8D4", secondary: "#FDBA74", accent: "#FDE047" },
      { primary: "#BE123C", secondary: "#EA580C", accent: "#B45309" },
      { primary: "#E11D48", secondary: "#D97706", accent: "#92400E" },
    ],
  },

  "warm-editorial": {
    id: "warm-editorial",
    label: "Warm Editorial",
    description: "Magazine-inspired warm neutrals and elegant typography.",
    isDarkUi: false,
    palette: {
      primary: "#92400E",
      secondary: "#DC2626",
      accent: "#EA580C",
      background: "#FEF5F1",
      surface: "#FFFBF0",
      surfaceAlt: "#F9E8E0",
      text: "#3730A3",
      textMuted: "#78716C",
      borderSubtle: "#EFDBCE",
      borderStrong: "#D97706",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 700, style: "italic" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 600, style: "normal" },
    },
    colorVariations: [
      { primary: "#92400E", secondary: "#DC2626", accent: "#EA580C" },
      { primary: "#B45309", secondary: "#E11D48", accent: "#F97316" },
      { primary: "#D97706", secondary: "#BE123C", accent: "#FB923C" },
      { primary: "#F59E0B", secondary: "#7C2D12", accent: "#FDBA74" },
      { primary: "#FBBF24", secondary: "#78716C", accent: "#FCD34D" },
    ],
  },

  "retro-pixel": {
    id: "retro-pixel",
    label: "Retro Pixel",
    description: "Bold primaries, chunky shapes and nostalgic UI.",
    isDarkUi: false,
    palette: {
      primary: "#DC2626",
      secondary: "#1E40AF",
      accent: "#FBBF24",
      background: "#FEF3C7",
      surface: "#FFFFFF",
      surfaceAlt: "#FEF08A",
      text: "#0F172A",
      textMuted: "#4B5563",
      borderSubtle: "#FDE68A",
      borderStrong: "#111827",
    },
    ui: {
      buttonPrimary: { radius: "none", shadow: "strong", border: "strong" },
      buttonSecondary: { radius: "none", shadow: "strong", border: "strong" },
      card: { radius: "none", shadow: "strong", border: "strong" },
    },
    typography: {
      heading: { size: "2xl", weight: 800, style: "normal" },
      body: { size: "sm", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 700, style: "normal" },
    },
    colorVariations: [
      { primary: "#DC2626", secondary: "#1E40AF", accent: "#FBBF24" },
      { primary: "#EF4444", secondary: "#1D4ED8", accent: "#FCD34D" },
      { primary: "#F87171", secondary: "#3B82F6", accent: "#FBBF24" },
      { primary: "#B91C1C", secondary: "#1E3A8A", accent: "#FBBF24" },
      { primary: "#991B1B", secondary: "#1E293B", accent: "#FBBF24" },
    ],
  },

  "magazine-brutalism": {
    id: "magazine-brutalism",
    label: "Magazine Brutalism",
    description: "Huge headlines, sharp grids and editorial contrast.",
    isDarkUi: false,
    palette: {
      primary: "#111827",
      secondary: "#6B7280",
      accent: "#F97316",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#F3F4F6",
      text: "#000000",
      textMuted: "#4B5563",
      borderSubtle: "#E5E7EB",
      borderStrong: "#000000",
    },
    ui: {
      buttonPrimary: { radius: "none", shadow: "none", border: "strong" },
      buttonSecondary: { radius: "none", shadow: "none", border: "strong" },
      card: { radius: "none", shadow: "none", border: "strong" },
    },
    typography: {
      heading: { size: "2xl", weight: 800, style: "normal" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 700, style: "normal" },
    },
    colorVariations: [
      { primary: "#111827", secondary: "#6B7280", accent: "#F97316" },
      { primary: "#1F2937", secondary: "#9CA3AF", accent: "#FB923C" },
      { primary: "#000000", secondary: "#4B5563", accent: "#FDBA74" },
      { primary: "#0F172A", secondary: "#78716C", accent: "#FCD34D" },
      { primary: "#1A202C", secondary: "#64748B", accent: "#FBBF24" },
    ],
  },

  "cyber-mint": {
    id: "cyber-mint",
    label: "Cyber Mint",
    description: "High-contrast dark UI with fresh mint and aqua accents.",
    isDarkUi: true,
    palette: {
      primary: "#06B6D4",
      secondary: "#10B981",
      accent: "#00FF00",
      background: "#0A0E27",
      surface: "#0F1729",
      surfaceAlt: "#1A2332",
      text: "#FFFFFF",
      textMuted: "#94A3B8",
      borderSubtle: "#1A2332",
      borderStrong: "#06B6D4",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "strong", border: "subtle" },
    },
    typography: {
      heading: { size: "2xl", weight: 700, style: "normal" },
      body: { size: "md", weight: 400, style: "normal" },
      accent: { size: "sm", weight: 600, style: "normal" },
    },
    colorVariations: [
      { primary: "#06B6D4", secondary: "#10B981", accent: "#00FF00" },
      { primary: "#22D3EE", secondary: "#34D399", accent: "#7FFF00" },
      { primary: "#67E8F9", secondary: "#6EE7B7", accent: "#ADFF2F" },
      { primary: "#0891B2", secondary: "#059669", accent: "#00B300" },
      { primary: "#0E7490", secondary: "#047857", accent: "#007700" },
    ],
  },
};
