import type { VibePreset, VibeId } from "./types";

export const VIBE_PRESETS: Record<VibeId, VibePreset> = {
  minimal: {
    id: "minimal",
    label: "Minimal",
    description: "Soft neutrals, subtle borders and calm UI surfaces.",
    isDarkUi: false,
    palette: {
      primary: "#0F766E",
      secondary: "#475569",
      accent: "#F97316",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#E5E7EB",
      text: "#020617",
      textMuted: "#64748B",
      borderSubtle: "#E5E7EB",
      borderStrong: "#CBD5F5",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
  },

  "modern-saas": {
    id: "modern-saas",
    label: "Modern SaaS",
    description:
      "Bright primary, layered cards and rounded buttons for product UIs.",
    isDarkUi: false,
    palette: {
      primary: "#2563EB",
      secondary: "#4F46E5",
      accent: "#F97316",
      background: "#F3F4F6",
      surface: "#FFFFFF",
      surfaceAlt: "#E5E7EB",
      text: "#020617",
      textMuted: "#6B7280",
      borderSubtle: "#E5E7EB",
      borderStrong: "#CBD5F5",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
  },

  brutalist: {
    id: "brutalist",
    label: "Brutalist",
    description: "Sharp corners, strong borders and unapologetic colors.",
    isDarkUi: false,
    palette: {
      primary: "#111827",
      secondary: "#F97316",
      accent: "#EC4899",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#F3F4F6",
      text: "#020617",
      textMuted: "#4B5563",
      borderSubtle: "#E5E7EB",
      borderStrong: "#111827",
    },
    ui: {
      buttonPrimary: { radius: "none", shadow: "none", border: "strong" },
      buttonSecondary: { radius: "none", shadow: "none", border: "strong" },
      card: { radius: "sm", shadow: "none", border: "strong" },
    },
  },

  pastel: {
    id: "pastel",
    label: "Pastel / Friendly",
    description: "Soft backgrounds, candy accents and rounded pill buttons.",
    isDarkUi: false,
    palette: {
      primary: "#FB7185",
      secondary: "#38BDF8",
      accent: "#A78BFA",
      background: "#FEFCE8",
      surface: "#FFFBEB",
      surfaceAlt: "#F9FAFB",
      text: "#1F2933",
      textMuted: "#6B7280",
      borderSubtle: "#FDE68A",
      borderStrong: "#F97373",
    },
    ui: {
      buttonPrimary: { radius: "full", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "full", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
  },

  "dark-tech": {
    id: "dark-tech",
    label: "Dark Tech",
    description: "Deep dark surfaces with neon-like accents.",
    isDarkUi: true,
    palette: {
      primary: "#38BDF8",
      secondary: "#6366F1",
      accent: "#22C55E",
      background: "#020617",
      surface: "#020617",
      surfaceAlt: "#0F172A",
      text: "#E5E7EB",
      textMuted: "#9CA3AF",
      borderSubtle: "#1E293B",
      borderStrong: "#38BDF8",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
  },

  luxury: {
    id: "luxury",
    label: "Luxury",
    description: "Deep backgrounds, gold accents and high-contrast serifs.",
    isDarkUi: true,
    palette: {
      primary: "#D4AF37",
      secondary: "#F97316",
      accent: "#ECFEFF",
      background: "#020617",
      surface: "#020617",
      surfaceAlt: "#111827",
      text: "#F9FAFB",
      textMuted: "#9CA3AF",
      borderSubtle: "#1F2937",
      borderStrong: "#D4AF37",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
  },

  "soft-neo-tech": {
    id: "soft-neo-tech",
    label: "Soft Neo-Tech",
    description: "Soft dark UI with muted neons and rounded surfaces.",
    isDarkUi: true,
    palette: {
      primary: "#22D3EE",
      secondary: "#A855F7",
      accent: "#67E8F9",
      background: "#020617",
      surface: "#020617",
      surfaceAlt: "#0B1120",
      text: "#E5E7EB",
      textMuted: "#94A3B8",
      borderSubtle: "#1E293B",
      borderStrong: "#22D3EE",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
  },

  "gradient-bloom": {
    id: "gradient-bloom",
    label: "Gradient Bloom",
    description: "Bright gradients and playful landing-page energy.",
    isDarkUi: false,
    palette: {
      primary: "#EC4899",
      secondary: "#6366F1",
      accent: "#F97316",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#EEF2FF",
      text: "#020617",
      textMuted: "#6B7280",
      borderSubtle: "#E5E7EB",
      borderStrong: "#EC4899",
    },
    ui: {
      buttonPrimary: { radius: "lg", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "lg", shadow: "none", border: "subtle" },
      card: { radius: "xl", shadow: "soft", border: "subtle" },
    },
  },

  "warm-editorial": {
    id: "warm-editorial",
    label: "Warm Editorial",
    description: "Magazine-inspired warm neutrals and elegant typography.",
    isDarkUi: false,
    palette: {
      primary: "#D97706",
      secondary: "#92400E",
      accent: "#10B981",
      background: "#FFFBEB",
      surface: "#FEF3C7",
      surfaceAlt: "#FFF7ED",
      text: "#111827",
      textMuted: "#6B7280",
      borderSubtle: "#FBBF24",
      borderStrong: "#D97706",
    },
    ui: {
      buttonPrimary: { radius: "sm", shadow: "soft", border: "none" },
      buttonSecondary: { radius: "sm", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
  },

  "retro-pixel": {
    id: "retro-pixel",
    label: "Retro Pixel",
    description: "Bold primaries, chunky shapes and nostalgic UI.",
    isDarkUi: true,
    palette: {
      primary: "#F97316",
      secondary: "#22C55E",
      accent: "#3B82F6",
      background: "#020617",
      surface: "#020617",
      surfaceAlt: "#111827",
      text: "#F9FAFB",
      textMuted: "#9CA3AF",
      borderSubtle: "#1F2937",
      borderStrong: "#F97316",
    },
    ui: {
      buttonPrimary: { radius: "none", shadow: "strong", border: "strong" },
      buttonSecondary: { radius: "none", shadow: "none", border: "strong" },
      card: { radius: "none", shadow: "none", border: "strong" },
    },
  },

  "magazine-brutalism": {
    id: "magazine-brutalism",
    label: "Magazine Brutalism",
    description: "Huge headlines, sharp grids and editorial contrast.",
    isDarkUi: false,
    palette: {
      primary: "#111827",
      secondary: "#BE123C",
      accent: "#F97316",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceAlt: "#F3F4F6",
      text: "#020617",
      textMuted: "#4B5563",
      borderSubtle: "#E5E7EB",
      borderStrong: "#111827",
    },
    ui: {
      buttonPrimary: { radius: "sm", shadow: "none", border: "strong" },
      buttonSecondary: { radius: "sm", shadow: "none", border: "strong" },
      card: { radius: "sm", shadow: "none", border: "strong" },
    },
  },

  "cyber-mint": {
    id: "cyber-mint",
    label: "Cyber Mint",
    description: "High-contrast dark UI with fresh mint and aqua accents.",
    isDarkUi: true,
    palette: {
      primary: "#22C55E",
      secondary: "#2DD4BF",
      accent: "#38BDF8",
      background: "#020617",
      surface: "#020617",
      surfaceAlt: "#022C22",
      text: "#E5E7EB",
      textMuted: "#A7F3D0",
      borderSubtle: "#064E3B",
      borderStrong: "#22C55E",
    },
    ui: {
      buttonPrimary: { radius: "md", shadow: "strong", border: "none" },
      buttonSecondary: { radius: "md", shadow: "none", border: "subtle" },
      card: { radius: "lg", shadow: "soft", border: "subtle" },
    },
  },
};
